# fly.toml app configuration file generated for phone-book-peogway on 2025-09-01T06:44:36+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phone-book-peogway'
primary_region = 'arn'

[env]
  PORT = "3001" # add this where PORT matches the internal_port below

[processes]
  app = "node index.js" # add this

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/health"

[deploy]
	strategy = "canary"
